Traceback (most recent call last):
  File "/Users/tyler/.micromamba/envs/dtl2024/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/tyler/.micromamba/envs/dtl2024/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tyler/.micromamba/envs/dtl2024/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tyler/.micromamba/envs/dtl2024/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/tyler/.micromamba/envs/dtl2024/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/tyler/.micromamba/envs/dtl2024/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/tyler/.micromamba/envs/dtl2024/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Get the embeddings
paris, france = glove["paris"], glove["france"]
berlin, germany = glove["berlin"], glove["germany"]

# Create a target and stack the five vectors
target = (berlin - paris) + france
stacked = np.vstack([paris, france, berlin, germany, target])

# Plot
scatter_2d(stacked, norm = False, highlight = [4], figsize = (3, 3))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[41], line 10[0m
[1;32m      7[0m stacked [38;5;241m=[39m np[38;5;241m.[39mvstack([paris, france, berlin, germany, target])
[1;32m      9[0m [38;5;66;03m# Plot[39;00m
[0;32m---> 10[0m [43mscatter_2d[49m[43m([49m[43mstacked[49m[43m,[49m[43m [49m[43mnorm[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;28;43;01mFalse[39;49;00m[43m,[49m[43m [49m[43mhighlight[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[43m[[49m[38;5;241;43m4[39;49m[43m][49m[43m,[49m[43m [49m[43mfigsize[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[43m([49m[38;5;241;43m3[39;49m[43m,[49m[43m [49m[38;5;241;43m3[39;49m[43m)[49m[43m)[49m

Cell [0;32mIn[4], line 35[0m, in [0;36mscatter_2d[0;34m(matrix, norm, highlight, figsize)[0m
[1;32m     31[0m sns[38;5;241m.[39mscatterplot(
[1;32m     32[0m     x [38;5;241m=[39m [38;5;124m"[39m[38;5;124mx[39m[38;5;124m"[39m, y [38;5;241m=[39m [38;5;124m"[39m[38;5;124my[39m[38;5;124m"[39m, color [38;5;241m=[39m [38;5;124m"[39m[38;5;124mred[39m[38;5;124m"[39m, data [38;5;241m=[39m selected
[1;32m     33[0m )
[1;32m     34[0m [38;5;28;01mfor[39;00m idx [38;5;129;01min[39;00m highlight:
[0;32m---> 35[0m     label [38;5;241m=[39m [43mmatrix[49m[38;5;241;43m.[39;49m[43mindex[49m[idx]
[1;32m     36[0m     x, y [38;5;241m=[39m selected[38;5;241m.[39mloc[idx, [38;5;124m"[39m[38;5;124mx[39m[38;5;124m"[39m], selected[38;5;241m.[39mloc[idx, [38;5;124m"[39m[38;5;124my[39m[38;5;124m"[39m]
[1;32m     37[0m     plt[38;5;241m.[39mannotate(
[1;32m     38[0m         label,
[1;32m     39[0m         (x, y),
[0;32m   (...)[0m
[1;32m     42[0m         ha [38;5;241m=[39m [38;5;124m"[39m[38;5;124mcenter[39m[38;5;124m"[39m
[1;32m     43[0m     )

[0;31mAttributeError[0m: 'numpy.ndarray' object has no attribute 'index'

